const SVG_NS = "http://www.w3.org/2000/svg";

const ALLOWED_ELEMENTS = new Set([
  "svg",
  "g",
  "a",
  "circle",
  "ellipse",
  "line",
  "path",
  "polygon",
  "polyline",
  "rect",
  "text",
  "title",
]);

const ALLOWED_ATTRIBUTES = new Set([
  "class",
  "cx",
  "cy",
  "d",
  "fill",
  "font-family",
  "font-size",
  "font-style",
  "font-weight",
  "height",
  "id",
  "points",
  "preserveAspectRatio",
  "rx",
  "ry",
  "stroke",
  "stroke-dasharray",
  "stroke-linecap",
  "stroke-linejoin",
  "stroke-width",
  "target",
  "text-anchor",
  "transform",
  "viewBox",
  "width",
  "x",
  "x1",
  "x2",
  "xlink:title",
  "xml:space",
  "xmlns",
  "xmlns:xlink",
  "y",
  "y1",
  "y2",
]);

/** Protocols deliberately allowed for links generated by DOT's URL attribute. */
const SAFE_LINK_PROTOCOLS = new Set([
  "http",
  "https",
  "mailto",
  "obsidian",
]);

export function isSafeSvgHref(value: string): boolean {
  const href = value.trim();
  if (href.startsWith("#")) return true;
  const scheme = /^([A-Za-z][A-Za-z0-9+.-]*):/.exec(href);
  return scheme !== null && SAFE_LINK_PROTOCOLS.has(scheme[1].toLowerCase());
}

/**
 * Apply a strict Graphviz-SVG allowlist before an element reaches the live DOM.
 * Unknown elements and attributes (including event handlers, style, foreign
 * content, images, and unsafe link protocols) are removed.
 */
export function sanitizeSvg(root: Element): Element {
  const elements = [root, ...Array.from(root.getElementsByTagName("*"))];
  for (const element of elements) {
    if (
      element.namespaceURI !== SVG_NS ||
      !ALLOWED_ELEMENTS.has(element.localName)
    ) {
      if (element !== root) element.parentNode?.removeChild(element);
      continue;
    }

    for (const attribute of Array.from(element.attributes)) {
      const name = attribute.name;
      const isHref = name === "href" || name === "xlink:href";
      if (
        (isHref &&
          element.localName === "a" &&
          isSafeSvgHref(attribute.value)) ||
        (!isHref && ALLOWED_ATTRIBUTES.has(name))
      ) {
        continue;
      }
      element.removeAttributeNode(attribute);
    }
  }
  return root;
}

export function parseAndSanitizeSvg(svg: string): Element {
  const doc = new DOMParser().parseFromString(svg, "image/svg+xml");
  const root = doc.documentElement;
  if (
    root.namespaceURI !== SVG_NS ||
    root.localName !== "svg" ||
    doc.getElementsByTagName("parsererror").length > 0
  ) {
    throw new Error("Graphviz returned output that is not valid SVG.");
  }
  return document.importNode(sanitizeSvg(root), true);
}
